# Controller Manager configuration
controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    ocs2_quadruped_controller:
      type: ocs2_quadruped_controller/Ocs2QuadrupedController

ocs2_quadruped_controller:
  ros__parameters:
    update_rate: 1000  # Hz
    default_kp: 0.0
    default_kd: 5.0

    joints:
      - FL_abd_joint
      - FL_hip_joint
      - FL_knee_joint
      - FR_abd_joint
      - FR_hip_joint
      - FR_knee_joint
      - HL_abd_joint
      - HL_hip_joint
      - HL_knee_joint
      - HR_abd_joint
      - HR_hip_joint
      - HR_knee_joint

    command_interfaces:
      - effort
      - position
      - velocity
      - kp
      - kd

    state_interfaces:
      - effort
      - position
      - velocity

    feet:
      - FL_foot_link
      - FR_foot_link
      - HL_foot_link
      - HR_foot_link

    imu_name: "imu_sensor"
    base_name: "base_link"

    imu_interfaces:
      - orientation.w
      - orientation.x
      - orientation.y
      - orientation.z
      - angular_velocity.x
      - angular_velocity.y
      - angular_velocity.z
      - linear_acceleration.x
      - linear_acceleration.y
      - linear_acceleration.z

    # foot_force_name: "foot_contact_sensor"
    # foot_force_interfaces:
    #   - FL_foot_link
    #   - HL_foot_link
    #   - FR_foot_link
    #   - HR_foot_link